name: workflow

on:
  push

env:
  role-to-assume: arn:aws:iam::248606432711:role/ExecuteGithubActionsWithOidcRole

permissions:
  id-token: write
  contents: write

jobs:
  terraform:
    name: Terraform
    timeout-minutes: 10
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
          role-to-assume: ${{ env.role-to-assume }}
          role-session-name: cheke-ci
          aws-region: ap-northeast-1

    - name: terraform validate
      id: validate
      run: echo "OK"
      continue-on-error: true